name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://discord.gg/druweDMn3s)
        Feel free to check out other cool repositories of the Design and Code Community [here](https://github.com/Design-and-Code)
